//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/PlayerInputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputController"",
    ""maps"": [
        {
            ""name"": ""Battle"",
            ""id"": ""9f22a183-60d6-485b-bff6-96a1c903c33f"",
            ""actions"": [
                {
                    ""name"": ""Fast Attack"",
                    ""type"": ""Button"",
                    ""id"": ""16efb73e-37b1-4ed2-a335-c8f790f42ce7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Press Fast Attack"",
                    ""type"": ""Button"",
                    ""id"": ""0d02ef17-d9a1-4dc9-afc8-f6f996d8a7ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Release Fast Attack"",
                    ""type"": ""Button"",
                    ""id"": ""46ba934a-3d46-4f9e-800f-9c455d729ae5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Charged Move 1"",
                    ""type"": ""Button"",
                    ""id"": ""a83c95ab-3ef2-4808-b3cf-85f3a3773e21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Charged Move 2"",
                    ""type"": ""Button"",
                    ""id"": ""83840e90-2457-4f17-82c4-10855165f6b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 1"",
                    ""type"": ""Button"",
                    ""id"": ""209a9576-e01b-4b04-8d7d-36c963edae04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 2"",
                    ""type"": ""Button"",
                    ""id"": ""b27530c5-53b3-4101-b907-1fd30c5eb595"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 3"",
                    ""type"": ""Button"",
                    ""id"": ""d33b09ad-6e25-41ef-8e37-dae85b59487f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 4"",
                    ""type"": ""Button"",
                    ""id"": ""3b47ebee-5bc8-4755-a544-aff689ae12be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 5"",
                    ""type"": ""Button"",
                    ""id"": ""cca58a8d-6624-4db2-a114-b08eb657b614"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch 6"",
                    ""type"": ""Button"",
                    ""id"": ""4876a10e-e035-4f50-8a96-0cd055008f98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a67b1d20-a1af-4765-8990-e56ea2881c3e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fast Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d092d31a-a741-4d4d-adf2-62ac6891da82"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fast Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fa47097-ae9d-46ac-a10c-ff86a74d7f43"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Charged Move 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37e3f8eb-641f-43ee-aab2-67353cc5897f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Charged Move 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9efb6bc4-2c5e-4fa4-9b43-d1a3a52c4a2b"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Charged Move 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff7b1eee-3484-4c27-810b-14f15bbe0616"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Charged Move 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5421075-a9d4-4c31-91d8-09c0af7fa8c2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press Fast Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce932d9a-13e5-4b45-8707-70946aa40281"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press Fast Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5235425e-f31b-4b7e-ad81-76559271123a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Release Fast Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""331fdb6c-d306-49e9-8825-651228ade08a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Release Fast Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""056ef13b-d14d-41b8-bd0a-f558ab7991bf"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""844d2cd5-7919-4566-ae2f-e0439d2a3258"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be2c0fbf-fd12-4b51-921d-984259ff5215"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67d82e32-ce95-4347-beb6-045f230b6737"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df970256-5780-43dc-8c4a-09496de2ac40"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9d9c6b8-5cdc-4629-82e8-ec57598ec139"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9b20c4f-0d94-4493-bbee-cdeb933ad640"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch 6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Battle
        m_Battle = asset.FindActionMap("Battle", throwIfNotFound: true);
        m_Battle_FastAttack = m_Battle.FindAction("Fast Attack", throwIfNotFound: true);
        m_Battle_PressFastAttack = m_Battle.FindAction("Press Fast Attack", throwIfNotFound: true);
        m_Battle_ReleaseFastAttack = m_Battle.FindAction("Release Fast Attack", throwIfNotFound: true);
        m_Battle_ChargedMove1 = m_Battle.FindAction("Charged Move 1", throwIfNotFound: true);
        m_Battle_ChargedMove2 = m_Battle.FindAction("Charged Move 2", throwIfNotFound: true);
        m_Battle_Switch1 = m_Battle.FindAction("Switch 1", throwIfNotFound: true);
        m_Battle_Switch2 = m_Battle.FindAction("Switch 2", throwIfNotFound: true);
        m_Battle_Switch3 = m_Battle.FindAction("Switch 3", throwIfNotFound: true);
        m_Battle_Switch4 = m_Battle.FindAction("Switch 4", throwIfNotFound: true);
        m_Battle_Switch5 = m_Battle.FindAction("Switch 5", throwIfNotFound: true);
        m_Battle_Switch6 = m_Battle.FindAction("Switch 6", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Battle
    private readonly InputActionMap m_Battle;
    private List<IBattleActions> m_BattleActionsCallbackInterfaces = new List<IBattleActions>();
    private readonly InputAction m_Battle_FastAttack;
    private readonly InputAction m_Battle_PressFastAttack;
    private readonly InputAction m_Battle_ReleaseFastAttack;
    private readonly InputAction m_Battle_ChargedMove1;
    private readonly InputAction m_Battle_ChargedMove2;
    private readonly InputAction m_Battle_Switch1;
    private readonly InputAction m_Battle_Switch2;
    private readonly InputAction m_Battle_Switch3;
    private readonly InputAction m_Battle_Switch4;
    private readonly InputAction m_Battle_Switch5;
    private readonly InputAction m_Battle_Switch6;
    public struct BattleActions
    {
        private @PlayerInputController m_Wrapper;
        public BattleActions(@PlayerInputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @FastAttack => m_Wrapper.m_Battle_FastAttack;
        public InputAction @PressFastAttack => m_Wrapper.m_Battle_PressFastAttack;
        public InputAction @ReleaseFastAttack => m_Wrapper.m_Battle_ReleaseFastAttack;
        public InputAction @ChargedMove1 => m_Wrapper.m_Battle_ChargedMove1;
        public InputAction @ChargedMove2 => m_Wrapper.m_Battle_ChargedMove2;
        public InputAction @Switch1 => m_Wrapper.m_Battle_Switch1;
        public InputAction @Switch2 => m_Wrapper.m_Battle_Switch2;
        public InputAction @Switch3 => m_Wrapper.m_Battle_Switch3;
        public InputAction @Switch4 => m_Wrapper.m_Battle_Switch4;
        public InputAction @Switch5 => m_Wrapper.m_Battle_Switch5;
        public InputAction @Switch6 => m_Wrapper.m_Battle_Switch6;
        public InputActionMap Get() { return m_Wrapper.m_Battle; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BattleActions set) { return set.Get(); }
        public void AddCallbacks(IBattleActions instance)
        {
            if (instance == null || m_Wrapper.m_BattleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BattleActionsCallbackInterfaces.Add(instance);
            @FastAttack.started += instance.OnFastAttack;
            @FastAttack.performed += instance.OnFastAttack;
            @FastAttack.canceled += instance.OnFastAttack;
            @PressFastAttack.started += instance.OnPressFastAttack;
            @PressFastAttack.performed += instance.OnPressFastAttack;
            @PressFastAttack.canceled += instance.OnPressFastAttack;
            @ReleaseFastAttack.started += instance.OnReleaseFastAttack;
            @ReleaseFastAttack.performed += instance.OnReleaseFastAttack;
            @ReleaseFastAttack.canceled += instance.OnReleaseFastAttack;
            @ChargedMove1.started += instance.OnChargedMove1;
            @ChargedMove1.performed += instance.OnChargedMove1;
            @ChargedMove1.canceled += instance.OnChargedMove1;
            @ChargedMove2.started += instance.OnChargedMove2;
            @ChargedMove2.performed += instance.OnChargedMove2;
            @ChargedMove2.canceled += instance.OnChargedMove2;
            @Switch1.started += instance.OnSwitch1;
            @Switch1.performed += instance.OnSwitch1;
            @Switch1.canceled += instance.OnSwitch1;
            @Switch2.started += instance.OnSwitch2;
            @Switch2.performed += instance.OnSwitch2;
            @Switch2.canceled += instance.OnSwitch2;
            @Switch3.started += instance.OnSwitch3;
            @Switch3.performed += instance.OnSwitch3;
            @Switch3.canceled += instance.OnSwitch3;
            @Switch4.started += instance.OnSwitch4;
            @Switch4.performed += instance.OnSwitch4;
            @Switch4.canceled += instance.OnSwitch4;
            @Switch5.started += instance.OnSwitch5;
            @Switch5.performed += instance.OnSwitch5;
            @Switch5.canceled += instance.OnSwitch5;
            @Switch6.started += instance.OnSwitch6;
            @Switch6.performed += instance.OnSwitch6;
            @Switch6.canceled += instance.OnSwitch6;
        }

        private void UnregisterCallbacks(IBattleActions instance)
        {
            @FastAttack.started -= instance.OnFastAttack;
            @FastAttack.performed -= instance.OnFastAttack;
            @FastAttack.canceled -= instance.OnFastAttack;
            @PressFastAttack.started -= instance.OnPressFastAttack;
            @PressFastAttack.performed -= instance.OnPressFastAttack;
            @PressFastAttack.canceled -= instance.OnPressFastAttack;
            @ReleaseFastAttack.started -= instance.OnReleaseFastAttack;
            @ReleaseFastAttack.performed -= instance.OnReleaseFastAttack;
            @ReleaseFastAttack.canceled -= instance.OnReleaseFastAttack;
            @ChargedMove1.started -= instance.OnChargedMove1;
            @ChargedMove1.performed -= instance.OnChargedMove1;
            @ChargedMove1.canceled -= instance.OnChargedMove1;
            @ChargedMove2.started -= instance.OnChargedMove2;
            @ChargedMove2.performed -= instance.OnChargedMove2;
            @ChargedMove2.canceled -= instance.OnChargedMove2;
            @Switch1.started -= instance.OnSwitch1;
            @Switch1.performed -= instance.OnSwitch1;
            @Switch1.canceled -= instance.OnSwitch1;
            @Switch2.started -= instance.OnSwitch2;
            @Switch2.performed -= instance.OnSwitch2;
            @Switch2.canceled -= instance.OnSwitch2;
            @Switch3.started -= instance.OnSwitch3;
            @Switch3.performed -= instance.OnSwitch3;
            @Switch3.canceled -= instance.OnSwitch3;
            @Switch4.started -= instance.OnSwitch4;
            @Switch4.performed -= instance.OnSwitch4;
            @Switch4.canceled -= instance.OnSwitch4;
            @Switch5.started -= instance.OnSwitch5;
            @Switch5.performed -= instance.OnSwitch5;
            @Switch5.canceled -= instance.OnSwitch5;
            @Switch6.started -= instance.OnSwitch6;
            @Switch6.performed -= instance.OnSwitch6;
            @Switch6.canceled -= instance.OnSwitch6;
        }

        public void RemoveCallbacks(IBattleActions instance)
        {
            if (m_Wrapper.m_BattleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBattleActions instance)
        {
            foreach (var item in m_Wrapper.m_BattleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BattleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BattleActions @Battle => new BattleActions(this);
    public interface IBattleActions
    {
        void OnFastAttack(InputAction.CallbackContext context);
        void OnPressFastAttack(InputAction.CallbackContext context);
        void OnReleaseFastAttack(InputAction.CallbackContext context);
        void OnChargedMove1(InputAction.CallbackContext context);
        void OnChargedMove2(InputAction.CallbackContext context);
        void OnSwitch1(InputAction.CallbackContext context);
        void OnSwitch2(InputAction.CallbackContext context);
        void OnSwitch3(InputAction.CallbackContext context);
        void OnSwitch4(InputAction.CallbackContext context);
        void OnSwitch5(InputAction.CallbackContext context);
        void OnSwitch6(InputAction.CallbackContext context);
    }
}
